// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMIOMwt9N7UOIWdhacHAK2X0zQmNnAwo',
    appId: '1:363956885419:web:40d0455bef399c50d824ee',
    messagingSenderId: '363956885419',
    projectId: 'instagram-clone-6af59',
    authDomain: 'instagram-clone-6af59.firebaseapp.com',
    storageBucket: 'instagram-clone-6af59.firebasestorage.app',
    measurementId: 'G-TYGPL95TM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzKjLWEH00uYu61K9lMeF8EYPrhWQ6nAo',
    appId: '1:363956885419:android:573948328a621d65d824ee',
    messagingSenderId: '363956885419',
    projectId: 'instagram-clone-6af59',
    storageBucket: 'instagram-clone-6af59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3R_rk276SDWJFoOJH8dxrHx_hMspnF9o',
    appId: '1:363956885419:ios:d0a1c5bb281753c4d824ee',
    messagingSenderId: '363956885419',
    projectId: 'instagram-clone-6af59',
    storageBucket: 'instagram-clone-6af59.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3R_rk276SDWJFoOJH8dxrHx_hMspnF9o',
    appId: '1:363956885419:ios:d0a1c5bb281753c4d824ee',
    messagingSenderId: '363956885419',
    projectId: 'instagram-clone-6af59',
    storageBucket: 'instagram-clone-6af59.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnMIOMwt9N7UOIWdhacHAK2X0zQmNnAwo',
    appId: '1:363956885419:web:c4b991558b6dda8dd824ee',
    messagingSenderId: '363956885419',
    projectId: 'instagram-clone-6af59',
    authDomain: 'instagram-clone-6af59.firebaseapp.com',
    storageBucket: 'instagram-clone-6af59.firebasestorage.app',
    measurementId: 'G-7YY6HZLPN9',
  );
}
